apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-sneakers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-sneakers
  template:
    metadata:
      labels:
        app: react-sneakers
    spec:
      containers:
      - name: react-sneakers
        image: your-dockerhub-username/react-sneakers-app
        ports:
        - containerPort: 3000

