apiVersion: v1
kind: Service
metadata:
  name: sneakers-service
spec:
  type: NodePort
  selector:
    app: sneakers-app
  ports:
    - port: 80            # Kubernetes service port
      targetPort: 3000    # Port exposed by your container (React app)
      nodePort: 32000     # Port exposed on the cluster node

