apiVersion: v1
kind: Service
metadata:
  name: sneakers-service
spec:
  type: NodePort
  selector:
    app: react-sneakers
  ports:
    - port: 80    
      targetPort: 3000   
      nodePort: 32000   

